version: '3'
services:
  web:
    build:
      context: ./
    container_name: web
    volumes:
      - app_data:/web
    #    command: npm run dev:prod
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=real
volumes:
  app_data:
    driver: local
