version: '3'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
#    command: npm run dev:prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      BUILD_ENV: real
